Sales Illustration/Models/Log.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.Illustration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public string AgentCode { get; set; }
        public string AgentName { get; set; }
        public System.DateTime LoginTime { get; set; }
        public string Description { get; set; }
    
        public virtual UserMembership UserMembership { get; set; }
    }
}

Sales Illustration/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sales.Illustration.Web.Helper;

namespace Sales.Illustration.Web.Controllers
{
    public class LogController : Controller
    {
        Sales.Illustration.Web.Models.MainModel obj = new Models.MainModel();
        public class data
        {
            public string monthyear { get; set; }
        }
        public ActionResult Index()
        {
            var monthyear = _session.MonthYear == null || _session.MonthYear == "" ? DateTime.Now.ToString("MM-yyyy") : _session.MonthYear;
            ViewData["logdata"] = obj.GetLogHistory(monthyear);
            ViewData["monthyear"] = monthyear;
            
            return View();
        }

        [HttpPost]
        public ActionResult ValidateMonthYear(data data)
        {
            _session.MonthYear = data.monthyear;
            return RedirectToAction("Index");
        }
    }
}

Sales Illustration/Views/Log/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    
    var LogHistory = ViewData["logdata"] as IEnumerable<Sales.Illustration.Web.Models.Log>;
    int p = 1;
    try
    {
        p = Convert.ToInt16(Request.Params["p"] == null ? "1" : Request.Params["p"]);
    }
    catch { }
    int rowperpage = 10;
    var bagi = LogHistory.Count() / rowperpage;
    var sisa = LogHistory.Count() % rowperpage;
    var totalPage = 0;
    if (sisa != 0)
    {
        totalPage = bagi + 1;
    }
    else
    {
        totalPage = bagi;
    }
    if (p > totalPage) { p = totalPage; }
    if (p < 1) { p = 1; }
    int next = p + 1>totalPage ? totalPage : p+1;
    int previous = p - 1 < 1 ? 1 : p - 1;

    
}

@Html.Partial("Header")
<div id="wrapper" ng-app="myApp" ng-controller="myCtrl">
    @Html.Partial("SideBar")
    <div class="main-tittle">
        <center><h5 class="main-tittle"><b>DAFTAR LOG</b></h5></center>
    </div>
    <div class="main-content" style="margin-bottom:25px;">
        @using (Html.BeginForm("ValidateMonthYear", "Log", FormMethod.Post, new { @id = "form" }))
        {
        <div class="row">
            <div class="col-lg-12">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-8 jarak">
                    <div class="input-group monthpicker">
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                        <input id="monthyear" name="monthyear" type="text" placeholder="Bulan & Tahun" class="form-control" value="@ViewData["monthyear"]" />
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 jarak">
                    <button id="submit" class="btn btn-warning" onclick="submit()">
                        SUBMIT
                    </button>
                </div>
            </div>
        </div>
        }
        <div class="nav-divider"></div>
        <div class="row">
            <div class="col-lg-12">
                <div class="produk-header">
                    <h4><img src="/Content/dist/img/logo-warna.png">Login History</h4>
                </div>
                <div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 jarak">
                        <span class="text-md"> Total : @LogHistory.Count()</span>
                    </div>
                    <table class="table-ul table-bordered">
                        <thead>
                            <tr>
                                <th class="text-center">No</th>
                                <th class="text-center">Agent Code</th>
                                <th class="text-center">Nama Agent</th>
                                <th class="text-center">Waktu Login</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 1;
                                int min_page = (p-1)*rowperpage ;
                                int max_page = p*rowperpage;
                                foreach (var log in LogHistory)
                                {
                                    if (i > min_page && i <= max_page)
                                    { 
                                    <tr>
                                        <td style="font-weight: normal;">@i</td>
                                        <td style="font-weight: normal;">@log.AgentCode</td>
                                        <td style="font-weight: normal;">@log.AgentName</td>
                                        <td style="font-weight: normal;color:grey" class="text-center">@log.LoginTime</td>
                                    </tr>
                                    }
                                    i = i + 1;
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="div-nav-pro-bawah" style="margin-bottom:10px;">
        <div class="col-lg-12">
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-12 ul-btn-nav">
                @{
                    if (p <= 1) 
                    {<button id="content_save_prev" class="btn btn-warning" onclick="prev()" disabled="disable">PREV</button>}
                    else{
                    <button id="content_save_prev" class="btn btn-warning" onclick="prev()" >PREV</button>}
                }
                    
            </div>
            
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div id="msform-bawah">
                    <ul id="progressbar-bawah" style="padding-left:0px;">
                        @for (var iPage = 1; iPage <= totalPage; iPage++)
                        {
                            if (iPage == p)
                            {
                                <li class="active"></li>
                            }
                            else
                            {
                              <li></li>
                            }
                        }
                       
                    </ul>
                </div>
            </div>  
                   
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-12 ul-btn-nav">
                @{
                    if (p >= totalPage)
                    {<button id="content_save_next" class="btn btn-warning" onclick="next()" disabled="disable">NEXT</button>  }
                    else
                    {<button id="content_save_next" class="btn btn-warning" onclick="next()">NEXT</button>  }

}
                
            </div>
        </div>
    </div>
</div>
@Html.Partial("Footer")

<script type="text/javascript">    
    $(".monthpicker").datetimepicker({
        format: 'MM-YYYY',
        viewMode: "months"
    });

    function submit() {
        $("#form").submit();
    }

    function next() {
        window.location = "?p=@next";
    }
    function prev() { window.location = "?p=@previous"; }

</script>