Sales Illustration/Controllers/ReportController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Sales.Illustration.Web.Extensions;
using Sales.Illustration.Web.Helper;
using Sales.Illustration.Web.Services;
using Sales.Illustration.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using RestSharp;
using RestSharp.Authenticators;
using ParameterType = RestSharp.ParameterType;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.IdentityModel.Tokens;
using System.Security.Claims;
using System.Text;
using Newtonsoft.Json;
using Sales.Illustration.Web.Domain;

//System.IO.File.ReadAllBytes;

namespace Sales.Illustration.Web.Controllers
{
    public class ReportController : Controller
    {
        //
        // GET: /Report/

        public ActionResult Index()
        {
            return View();
        }

        [DeleteFile]
        public virtual FileResult Download()
        {
            var fullPath = Path.Combine(Server.MapPath("~/Report/temp"), _session.TransLogCode + ".pdf");
            var fi = new FileInfo(fullPath);

            return fi.Exists ? File(fullPath, System.Net.Mime.MediaTypeNames.Application.Octet, Path.GetFileName(fullPath)) : File(fullPath, System.Net.Mime.MediaTypeNames.Application.Octet, Path.GetFileName(RegenerateReport()));
        }

        [DeleteFile]
        public async Task<ActionResult> SendMail(SendMailViewModel model)
        {

            var email = ConfigurationManager.AppSettings["Email"];
            var password = ConfigurationManager.AppSettings["Password"];
            var host = ConfigurationManager.AppSettings["SMTP"];

            var message = new MailMessage();
            message.To.Add(new MailAddress(model.To));
            message.From = new MailAddress(email);
            message.Subject = model.Subject;
            message.Body = model.Body;
            message.IsBodyHtml = true;

            var fullPath = Path.Combine(Server.MapPath("~/Report/temp"), _session.TransLogCode + ".pdf");
            var fi = new FileInfo(fullPath);

            if (fi.Exists)
            {
                message.Attachments.Add(new Attachment(fullPath));
            }
            else
            {
                var path = RegenerateReport();
                message.Attachments.Add(new Attachment(path));
            }

            using (var smtp = new SmtpClient())
            {

                var credential = new NetworkCredential
                {
                    UserName = email,
                    Password = password
                };

                smtp.Credentials = credential;
                smtp.Host = host;
                smtp.Port = 25;
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.EnableSsl = false;

                try
                {
                    await smtp.SendMailAsync(message);
                    message.Attachments.Dispose();

                }
                catch (Exception) { }

                if (model.Source.Equals("tra"))
                    return RedirectToAction("ResetAllData", "Traditional");
                else
                    return RedirectToAction("ResetAllData", "UnitLink");
            }
        }


        public async Task<ActionResult> SendApiInvitation(SendApiInvitationViewModel model)
        {
            apiInvitation result;
            var serverDeploy = ConfigurationManager.AppSettings["ServerDeploy"];
            var client = new RestClient("http://192.168.0.220:8080/hanwhaservices/sis/invite");
            client.Timeout = -1;
            var request = new RestRequest(Method.POST);
            if (serverDeploy == "UAT")
            {
                request.AddHeader("token", "0LOjWiMnOxWfQuhDhpIn9wp2dS4J0wK7dEbK2y6W7L7VXv6teuV7SA2c14nvoFvH");
            }
            request.AddHeader("Content-Type", "application/json");

            var fullPath = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Report/temp"), _session.TransLogCode + ".pdf").Replace(@"\", "/");

            Byte[] bytes = System.IO.File.ReadAllBytes(fullPath);
            String file = Convert.ToBase64String(bytes);

            var body = @"
                            " + "\n" +
                                        @"{
                            " + "\n" +
                                        @"	""transCode"": """ + _session.TransLogCode + @""",
                            " + "\n" +
                                        @"	""emailAddress"": """ + model.CustomerAddress + @""",
                            " + "\n" +
                                        @"	""mobilePhone"": """ + model.Phone + @""",
                            " + "\n" +
                                        @"    ""streamIlustrasiFile"":""" + file + @""",
                            " + "\n" +
                                        @"    ""pathIlustrasiFile"":""" + fullPath + @"""
                            " + "\n" +
                 @"}";
            request.AddParameter("application/json", body, ParameterType.RequestBody);

            IRestResponse response = client.Execute(request);
            result = JsonConvert.DeserializeObject<apiInvitation>(response.Content);
            var statusCode = result.result_code;
            var mess = result.message;
            if (statusCode == 1000)
            {
                TempData["errorMsg"] = "Success";

                if (model.Source.Equals("tra"))
                    return RedirectToAction("ResetAllData", "Traditional");
                else if (model.Source.Equals("ul"))
                    return RedirectToAction("ResetAllData", "UnitLink");
                else
                    return RedirectToAction("ResetAllData", "Kesehatan");

            }
            else
            {
                TempData["errorMsg"] = "Failed. " + response.ErrorMessage + ".";

                if (model.Source.Equals("tra"))
                    return RedirectToAction("SendApiInvitation", "Traditional");
                else if (model.Source.Equals("ul"))
                    return RedirectToAction("SendApiInvitation", "UnitLink");
                else
                    return RedirectToAction("SendApiInvitation", "Kesehatan");
            }
        }

        private string RegenerateReport()
        {
            SummaryViewModel dataInput = new SummaryViewModel();
            dataInput.Nasabah = _session.dataNasabah;
            dataInput.Premi = _session.premiInvestmentData;
            dataInput.Rider = _session.riderData;
            dataInput.Additional = _session.addInsData;
            dataInput.TopUp = _session.topUpWithData;
            dataInput.Insurance = _session.insCostRatioData;

            if (_session.addInsData != null)
                dataInput.Additional = _session.addInsData;
            else
                dataInput.Additional = new AdditionalInsuredViewModel();

            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(dataInput.Insurance.Language);

            var result = MainServices.GenerateReport(dataInput, _session.AgentName, _session.AgentCode, _session.AppVersion);

            var rptH = new ReportDocument { FileName = Server.MapPath(string.Format("~/Report/{0}.rpt", result.ReportName)) };
            rptH.SetDataSource(result.IllustrationDataSet);

            var guid = _session.TransLogCode + ".pdf";
            var path = Path.Combine(Server.MapPath("~/Report/temp"), guid);
            rptH.ExportToDisk(ExportFormatType.PortableDocFormat, path);

            return path;
        }
    }
}

Sales Illustration/Controllers/TraditionalController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Sales.Illustration.Web.Domain;
using Sales.Illustration.Web.Extensions;
using Sales.Illustration.Web.Helper;
using Sales.Illustration.Web.Services;
using Sales.Illustration.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Sales.Illustration.Web.Controllers
{
    [SessionExpire]
    public class TraditionalController : Controller
    {
        Sales.Illustration.Web.Models.MainModel obj = new Sales.Illustration.Web.Models.MainModel();

        //
        // GET: /Traditional/

        public ActionResult Index()
        {
            _session.dataNasabah = null;
            _session.premiInvestmentData = null;
            _session.riderData = null;
            _session.insCostRatioData = null;
            _session.TransLogCode = null;
            _session.addInsTraditionalData = null;

            return RedirectToAction("NasabahData");
        }

        public ActionResult NasabahData()
        {
            var model = new NasabahDataViewModel();
            model.AgentType = _session.AgentType;
            ViewBag.TypeAgent = _session.AgentType;
            if (_session.dataNasabah != null)
                model = _session.dataNasabah;

            ViewData["riskClass"] = obj.GetActiveRiskClass().OrderBy(x => x.RiskClassDesc).Select(x => new SelectListItem { Text = x.RiskClassDesc, Value = x.RiskClassId.ToString() });
            ViewData["products"] = obj.GetProductByType("tra").OrderBy(x => x.OrderNo).Select(x => new SelectListItem { Text = x.ProductName, Value = x.ProductCode });

            return View("NasabahData", model);
        }

        [HttpPost]
        public ActionResult ValidateNasabahData(NasabahDataViewModel data)
        {
            if (data.TertanggungUtama == "Ya")
            {
                data.NamaTertanggungUtama = null;
                data.JenisKelaminTertanggungUtama = null;
                data.TanggalLahirTertanggungUtama = null;
                data.StatusPekerjaanTertanggungUtama = null;
                data.KelasPekerjaanTertanggungUtama = null;
                data.UmurTertanggungUtama = null;
                data.Relation = null;
            }
            else if ((data.NamaProduk == "HLGOLDENA" || data.NamaProduk == "HLGOLDENB") && (data.Relation == "Karyawan" || data.Relation == "Pengurus Yayasan"))
            {
                data.JenisKelaminPemegangPolis = null;
                data.TanggalLahirPemegangPolis = null;
                data.StatusPekerjaanPemegangPolis = null;
                data.KelasPekerjaanPemegangPolis = null;
                data.UmurPemegangPolis = 0;
            }

            _session.dataNasabah = data;

            return RedirectToAction("PremiumAndInvestment");
        }

        public ActionResult BackToNasabahData()
        {
            if (_session.premiInvestmentData != null)
                _session.premiInvestmentData = null;

            return RedirectToAction("NasabahData");
        }

        public ActionResult PremiumAndInvestment()
        {
            var model = new PremiumAndInvestmentViewModel();

            if (_session.premiInvestmentData != null)
            {
                model = _session.premiInvestmentData;
                model.additionalInsured = _session.addInsTraditionalData;
            }
            else
            {
                model.additionalInsured = new AdditionalInsuredTraditionalViewModel();
                model.additionalInsured.TertanggungTambahan = new List<AdditionalInsured>();
                var insured = new AdditionalInsured();
                model.additionalInsured.TertanggungTambahan.Add(insured);
            }

            var insAge = 0;
            if (_session.dataNasabah.TertanggungUtama == "Ya")
                insAge = Convert.ToInt32(_session.dataNasabah.UmurPemegangPolis);
            else
                insAge = Convert.ToInt32(_session.dataNasabah.UmurTertanggungUtama);

            model.AgentType =  _session.dataNasabah.AgentType;
            ViewBag.TypeAgent = _session.AgentType;
            model.additionalInsured.NasabahData = _session.dataNasabah;
            model.MataUang = "Rupiah";
            ViewData["insAge"] = insAge;
            ViewData["isTertanggungUtama"] = _session.dataNasabah.TertanggungUtama;
            ViewData["riskClass"] = obj.GetActiveRiskClass().OrderBy(x => x.RiskClassDesc).Select(x => new SelectListItem { Text = x.RiskClassDesc, Value = x.RiskClassId.ToString() });
            model.UsiaMasukAnak = _session.dataNasabah.UmurAnak;
            ViewData["paymentMethods"] = obj.GetActivePaymentMethod(_session.dataNasabah.NamaProduk).Select(x => new SelectListItem { Text = x.PMName, Value = x.PMCode.ToString() });
            var product = obj.GetProduct(_session.dataNasabah.NamaProduk);
            ViewData["ProductTitle"] = product.ProductName;
            ViewData["ProductCode"] = product.ProductCode;
            var pekerjaanP = obj.GetRiskClass(Convert.ToInt32(model.additionalInsured.NasabahData.StatusPekerjaanPemegangPolis));
            // ViewData["pekerjaanP"] = pekerjaanP.RiskClassDesc;
            ViewData["pekerjaanP"] = pekerjaanP == null ? "" : pekerjaanP.RiskClassDesc;
            var pekerjaanT = obj.GetRiskClass(Convert.ToInt32(model.additionalInsured.NasabahData.StatusPekerjaanTertanggungUtama));
            ViewData["pekerjaanT"] = model.additionalInsured.NasabahData.TertanggungUtama == "Ya" ? "" : pekerjaanT.RiskClassDesc;
            ViewData["jenisPlanX"] = obj.GetProductPlan(_session.dataNasabah.NamaProduk).Select(x => new SelectListItem { Text = x.PlanDesc, Value = x.PlanCode });
            //model.JenisPlan = "Gold";
            return View("PremiumAndInvestment", model);
        }

        [HttpPost]
        public ActionResult ValidatePremiumAndInvestmentData(PremiumAndInvestmentViewModel data, AdditionalInsuredTraditionalViewModel addins)
        {
            var redirect = "Rider";
            var product = obj.GetProduct(_session.dataNasabah.NamaProduk);
            _session.premiInvestmentData = data;
            _session.addInsTraditionalData = addins;

            if (product.ProductCode != "HLEDU" && product.ProductCode != "HSCI")
                redirect = "InsuranceCostAndRatio";

            if ((_session.dataNasabah.TertanggungUtama == "Ya" && _session.dataNasabah.UmurPemegangPolis <= 16) ||
                (_session.dataNasabah.TertanggungUtama != "Ya" && _session.dataNasabah.UmurTertanggungUtama <= 16))
            {
                if (product.ProductCode == "HLLIFE" && CalculatorServices.CurrencyToDecimal(data.UangPertanggungan) > 1500000000)
                {
                    TempData["errorMsg"] = "Maksimum Uang Pertanggungan untuk Tertanggung Utama Anak (Juvenile) adalah Rp 1.500.000.000";
                    return RedirectToAction("PremiumAndInvestment");
                }
            }

            return RedirectToAction(redirect);
        }

        public ActionResult BackToPremiumAndInvestment()
        {
            var product = obj.GetProduct(_session.dataNasabah.NamaProduk);
            if (_session.riderData != null)
                _session.riderData = null;

            if (_session.addInsData != null)
                _session.addInsData = null;

            if (product.ProductCode != "HLEDU" && _session.insCostRatioData != null)
                _session.insCostRatioData = null;

            return RedirectToAction("PremiumAndInvestment");
        }

        public ActionResult Rider()
        {
            var model = new RiderViewModel();

            if (_session.riderData != null)
            {
                model = _session.riderData;
            }
            else
            {
                var riders = obj.GetRiderByProduct(_session.dataNasabah.NamaProduk).GroupBy(x => x.RiderCode).Select(x => x.First());
                model.Riders = new List<Domain.RiderItem>();
                var totalBiayaAsuransi = 0;

                foreach (var rider in riders)
                {
                    List<Choices> choices = new List<Choices>();
                    var prod = obj.GetProduct(_session.dataNasabah.NamaProduk);
                    
                    var check = prod.ProductCategory.Equals("wizer") && (rider.RiderCode == "WOP" || rider.RiderCode == "ADB");
                    var uangPertanggungan = prod.ProductCategory.Equals("wizer") && (rider.RiderCode == "ADB") ? 3 * Int32.Parse(_session.premiInvestmentData.UangPertanggungan.Replace(",", "")) : 0;
                    var allocationPercent = prod.ProductCategory.Equals("wizer") && (rider.RiderCode == "ADB") ? "300%" : "0%";
                    var biayaAsuransi = prod.ProductCategory.Equals("wizer") && (rider.RiderCode == "ADB") ?
                        (int)MainServices.CalculateCostOfRider(new SummaryViewModel(), uangPertanggungan, rider.RiderCode,
                        null, _session.dataNasabah.UmurPemegangPolis, Int32.Parse(_session.dataNasabah.KelasPekerjaanPemegangPolis), rider.Category, prod, null) : 0;

                    var riderTypeList = obj.GetRiderProduct(prod.ProductCode, rider.RiderCode).Where(x => x.RiderTypeId != null).Select(x => x.RiderTypeId).ToList();

                    foreach (var c in rider.RiderTypes.Where(x => riderTypeList.Contains(x.RiderTypeId)))
                    {
                        var choice = new Choices();
                        choice.Checked = c.TypeName == "CI" && prod.ProductCategory.Equals("wizer");
                        choice.RiderType = c;

                        uangPertanggungan = choice.Checked ? Int32.Parse(_session.premiInvestmentData.UangPertanggungan.Replace(",", "")) : 0;
                        var dataInput = new SummaryViewModel();
                        var riderCode = rider.RiderCode;

Sales Illustration/Views/Traditional/Report.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string errorMsg = TempData["errorMsg"] != null ? TempData["errorMsg"].ToString() : "";
    string path = ViewData["path"].ToString().Replace("\\", "/");
    var pTitle = ViewData["ProductTitle"];
}

@Html.Partial("Header")
<div id="wrapper" ng-app="myApp" ng-controller="myCtrl">
    @Html.Partial("SideBar")
    <div class="main-tittle">
        <center><h5 class="main-tittle"><b>@pTitle</b></h5></center>
    </div>

    <div class="main-content" style="padding: 0px;">
        <div class="row">
            <div class="col-lg-12">
                <iframe width="100%" height="100%" src="@path"></iframe>
                <input type="hidden" id="hdErrorMsg" value="@errorMsg" />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 navigationbutton">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("ResetAllData", "Traditional")';">
                    CREATE NEW
                </button>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 btn-bawah-mid">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("Download", "Report")';">
                    SAVE PDF
                </button>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 btn-bawah-mid">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("SendMailReport", "Traditional")';">
                    EMAIL
                </button>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 btn-bawah-right">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("SendApiInvitation", "Traditional")';">
                    SEND INVITATION
                </button>
            </div>
        </div>
    </div>

</div>
@Html.Partial("Footer")

<script type="text/javascript">
    $(document).ready(function () {
        var msg = $('#hdErrorMsg').val();

        if (msg != null && msg != "") {
            alertify.alert(msg);
        }
    });
</script>

Sales Illustration/Views/Traditional/SendApiInvitation.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var pTitle = ViewData["productName"];
    var subject = ViewData["subject"];
    var attachment = ViewData["attachment"];
    string errorMsg = TempData["errorMsg"] != null ? TempData["errorMsg"].ToString() : "";
}
@model Sales.Illustration.Web.ViewModel.SendApiInvitationViewModel

@Html.Partial("Header")
<div id="wrapper" ng-app="myApp" ng-controller="myCtrl">
    @Html.Partial("SideBar")
    <div class="main-tittle">
        <center><h5 class="main-tittle"><b>@pTitle</b></h5></center>
    </div>

    <div class="main-content" style="padding: 0px;">
        <div class="row">
            <div class="col-lg-12">
                <div class="content-tittle-1">
                    <i class=""></i> Send Mail Report
                </div>
                @using (Html.BeginForm("SendApiInvitation", "Report", FormMethod.Post, new { @id = "form" }))
                {
                    <fieldset>
                        <div class="col-lg-12">
                            <div class="row row-form" style="margin:0px -30px;">
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Customer Email Address
                                        </label>
                                        <input type="hidden" id="hdErrorMsg" value="@errorMsg" />
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextBoxFor(m => m.CustomerAddress, new { @class = "form-control", @placeholder = "Mail To" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Customer Mobile Phone No
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                         @Html.TextBoxFor(m => m.Phone, new { @class = "form-control",  @placeholder = "0"})

                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Subject
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Attachment
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextBoxFor(m => m.Attachment, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Body
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextAreaFor(m => m.Body, new { @class = "form-control" })
                                        @Html.HiddenFor(m => m.Source)
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                }
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 navigationbutton">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("ResetAllData", "Traditional")';">
                    CREATE NEW
                </button>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 btn-bawah-mid">
                <button class="btn btn-warning" onclick="next()">
                    SEND INVITATION
                </button>
            </div>
        </div>
    </div>

</div>
@Html.Partial("Footer")

<script type="text/javascript">
    $('document').ready(function () {
        var msg = $('#hdErrorMsg').val();
        if (msg != null && msg != "") {
            alertify.alert(msg);
        }
    });

    $('#@Html.IdFor(m => m.Phone)').on('focusout change', function () {
        var z = $('#@Html.IdFor(m => m.Phone)').val();
        if (/\D/.test(z)) {
            alertify.alert("Nomor telepon harus angka");
            $('#@Html.IdFor(m => m.Phone)').val('');
        }
    });
    function next() {
        var Phone = $('#@Html.IdFor(m => m.Phone)').val();
        var CustAddress = $('#@Html.IdFor(m => m.CustomerAddress)').val();
        var Body = $('#@Html.IdFor(m => m.Body)').val();

        if (Phone != "" && CustAddress != "" && Body != "") {
            $("#form").submit();
        }
        else {
            alertify.alert("Mohon lengkapi data.");
        }
        
    }
</script>

Sales Illustration/Views/Traditional/SendMailReport.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var pTitle = ViewData["productName"];
    var subject = ViewData["subject"];
    var attachment = ViewData["attachment"];
}
@model Sales.Illustration.Web.ViewModel.SendMailViewModel

@Html.Partial("Header")
<div id="wrapper" ng-app="myApp" ng-controller="myCtrl">
    @Html.Partial("SideBar")
    <div class="main-tittle">
        <center><h5 class="main-tittle"><b>@pTitle</b></h5></center>
    </div>

    <div class="main-content" style="padding: 0px;">
        <div class="row">
            <div class="col-lg-12">
                <div class="content-tittle-1">
                    <i class=""></i> Send Mail Report
                </div>
                @using (Html.BeginForm("SendMail", "Report", FormMethod.Post, new { @id = "form" }))
                {
                    <fieldset>
                        <div class="col-lg-12">
                            <div class="row row-form" style="margin:0px -30px;">
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            To
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextBoxFor(m => m.To, new { @class = "form-control", @placeholder = "Mail To" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Subject
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Attachment
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextBoxFor(m => m.Attachment, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Body
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextAreaFor(m => m.Body, new { @class = "form-control" })
                                        @Html.HiddenFor(m => m.Source)
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                }
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 navigationbutton">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("ResetAllData", "Traditional")';">
                    CREATE NEW
                </button>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 btn-bawah-mid">
                <button class="btn btn-warning" onclick="next()">
                    SEND MAIL
                </button>
            </div>
        </div>
    </div>

</div>
@Html.Partial("Footer")

<script type="text/javascript">
    function next() {
        $("#form").submit();
    }
</script>